#include "Utilsv2.h"
#include <stdio.h>
#include <string.h>


/**
 * Global Context Fallback Slot (Hidden Injection System)
*/

static Context* _global_ctx = NULL;

void core_set_global_ctx(Context* ctx) {
    _global_ctx = ctx;
}

/**
 * ## Log Prefix - Internal - Static 
 */
static void print_prefix(LogType type) {
    switch (type) {
        case LOG_INFO:   printf(CORE_COLOR_GREEN  "[INFO] "  CORE_COLOR_RESET); 
            break;
        case LOG_WARN:   printf(CORE_COLOR_YELLOW "[WARN] "  CORE_COLOR_RESET); 
            break;
        case LOG_ERR:    printf(CORE_COLOR_RED    "[ERROR] " CORE_COLOR_RESET); 
            break;
        case LOG_DEBUG:  printf(CORE_COLOR_CYAN   "[DEBUG] " CORE_COLOR_RESET); 
            break;
        default:         printf("[LOG]:");
            break;
    }
}

/**
 * ## Context Finder - Internal - Static 
 * Returns NULL if ctx is NULL or key not found.
 */

static Var* ctx_find(Context* ctx, const char* key) {
    if (!ctx) return NULL;

    for (int i = 0; i < ctx->count; i++) {
        if (strcmp(ctx->vars[i].name, key) == 0)
            return &ctx->vars[i];
    }
    return NULL;
}


/**
 * ## Print Var - Internal - Static 
 * Print a Var using its type tag
 */
static void print_var(Var* v) {
    if (!v || !v->ptr) {
        printf("{null}");
        return;
    }

    switch(v->type) {
        case VAR_INT:       printf("%d", *(int*)        v->ptr);    break;
        case VAR_FLOAT:     printf("%f", *(float*)      v->ptr);    break;
        case VAR_STRING:    printf("%s", *(const char**)v->ptr);    break;
        case VAR_ARRAY:     printf("[array@%p]",        v->ptr);    break;
        case VAR_STRUCT:    printf("{struct@%p}",       v->ptr);    break;
        case VAR_ENUM:      printf("%d", *(int*)        v->ptr);    break;
        default:            printf("{unknown}");                    break;
    }
}

/**
 * ## core_print
 * 
 * Walk the format string character by character.
 * 
 * '{' found -> extract key -> 
 *                             pass 1: try context lookup (typed, safe)
 *                             pass 2: fall back to va_arg by type hint
 * anything else -> putchar
 */
void CORE_API core_print(LogType type, const char* string_fmt, Context* ctx, ...){
    
    if (!ctx) ctx = _global_ctx;

    printf("[CORE] ");

    print_prefix(type);

    va_list args;
    va_start(args, ctx); /* Pivot = ctx (last named param)*/

    const char* p = string_fmt;

    while (*p) {

        // Token Start
        if (*p == '{') {

            const char* start = p + 1;
            const char* end   = strchr(start, '}');

            if (!end) {
                printf("{error}");
                break;
            }
            
            int len = (int)(end - start);
            if (len <= 0 || len > 63){
                printf("{invalid}");
                p = end + 1;
                continue;
            }

            char key[64];
            strncpy(key, start, len);
            key[len] = '\0';

            /** ------------ Pass 1 Context Lookup(named variables)---------------- */
            /**--------------(Generated By Tom (Python - via scanner.py)) */
            Var* v = ctx_find(ctx, key);
            if (v) {
                print_var(v);
                p = end + 1;
                continue;
            }

                /** ------------ Pass 2 type-hint -> va_arg ---------------- */
                /**Key is the type hint when ctx is NULL or key not in ctx */
                if      (strcmp(key, "int")     == 0)  printf("%d", va_arg(args, int));
                else if (strcmp(key, "float")   == 0)  printf("%f", va_arg(args, double)); // float promotes to double in ...(variadics)
                else if (strcmp(key, "string")  == 0)  printf("%s", va_arg(args, const char*)); 
                else                                   printf("{%s?}", key); // Unknown

                p = end + 1;
                continue;
        }
        // Normal Character
        putchar(*p);
        p++;
    } 

    va_end(args);
    putchar('\n');
}

/**
 * STUB
 * Supposed to resolve an Expression
 */
void* resolve_expr(Expr* expr, Context* ctx) {
    (void)expr;
    (void)ctx;
    return NULL;
}