#pragma once

#include <stdarg.h>


#ifdef __cplusplus
extern "C" {
#endif


/** 
 * Behind the Scenes
 * Look on this f-string style in C
 */


/**
 * ## Log Type
 * What kind of print it is.
 */
typedef enum LogType{
    LOG_INFO = 0,
    LOG_WARN = 1,
    LOG_ERR =  2,
    LOG_DEBUG = 3,
} LogType;  



/**
 * ## VarType
 * Tags carried by every Var(variable) so print_var can dispatch correctly.
 * Order is fixed - scanner.py and PyUtil depend on these values.
 */
typedef enum VarType{
    VAR_INT     =  0,
    VAR_FLOAT   =  1,
    VAR_STRING  =  2,
    VAR_CHAR    =  3,
    VAR_ARRAY   =  4,
    VAR_STRUCT  =  5,
    VAR_ENUM    =  6
} VarType;  

/**
 * ## Guard
 * If values ever shift the build breaks visibly
 */

#ifdef __cplusplus
    static_assert(VAR_INT == 0 && VAR_FLOAT == 1 && VAR_STRING == 2, 
                "VarType tag order changed -- sync PyUtil and scanner.py");
#else
    _Static_assert(VAR_INT == 0 && VAR_FLOAT == 1 && VAR_STRING == 2, 
                "VarType tag order changed -- sync PyUtil and scanner.py");
#endif



/**
 * ## Var (Varible)
 * One Entry in the context registry.
 * ptr always points to the live variables - never a copy (exactly as they are in the file)
 * MetaData fields (is_array, etc.) are populated by PyUtil / Scanner.
 */
typedef struct {    
    const char* name;
    VarType     type; // 0 - Int, 1 - Float, 2 = String
    void*       ptr;
    
    /** PyUtil Metadata - populated by generated_ctx.c */
    int         is_array;
    int         is_struct;
    int         is_enum;
} Var;

/**
 * ## Context
 * Passed to core_print. Generated by scanner.py + constructor.
 */
typedef struct Context{
    Var* vars;
    int count;
} Context;

/**
 * ## Expression
 * Parsed representation of a compound token: {arr[0]}, {player->hp}
 * Populated by PyUtil_ParseExpr. Resolved at runtime by resolve_expr.
 */
typedef struct Expr {
    const char* base;
    const char* key;
    int is_array;
} Expr;

/**
 * Runtime Resolver
 * Walks Context, finds base, resolves key
 * Implementation is in Utils.c; expression support is Phase 2
 */
void* resolve_expr(Expr* expr, Context* ctx);


/**
 * ## Ansi Colors
 */

#define CORE_COLOR_RESET        "\x1b[0m"

#define CORE_COLOR_RED          "\x1b[31m"   
#define CORE_COLOR_GREEN        "\x1b[32m"
#define CORE_COLOR_YELLOW       "\x1b[33m"
#define CORE_COLOR_BLUE         "\x1b[34m"
#define CORE_COLOR_MAGENTA      "\x1b[35m"
#define CORE_COLOR_CYAN         "\x1b[36m"
#define CORE_COLOR_WHITE        "\x1b[37m"



/**
 *  __cdecl portability
 * 
 * #### __core_cdecl: caller cleans the stack.
 *      Required for variadic fallback - callee cant know how many args were pushed
 * so it can't clean them up itself.
 * 
 * MSVC names it __cdecl. GCC on x64 has one calling convention
 * so the attribute is a no-op there - but we keep it in the 
 * declaration so the intent is documented and MSVC builds work.
 */
#ifdef _MSC_VER
    #define CORE_API __cdecl
#else
    #define CORE_API /** GCC/Clang already have a caller-cleanup on x86 by default */
#endif

/**
 * ## core_print
 * 
 * ### type - log_level
 * ### string_fmt - format string using {token} syntax
 * ### ctx - optional context.
 * ### ... - variadic fallback when ctx is NULL or key not found
 * 

 * 
 * #### Example Uses:
 *      core_print(LOG_INFO, "hp is {hp}", &ctx) // context path
 *      core_print(LOG_WARN, "val: {int}", NULL, 42) // variadic path
 *      core_print(LOG_ERR, "crash here", NULL) // plain string
 */
void CORE_API core_print(LogType type, const char* string_fmt, Context* ctx, ...);



/**
 * ## Set a Global Context (Automatic)
 * ### Notice:
 * #### Do not call by hand.
 * ### Info:
 * Registers a context as the global fallback.
 * Called automatically by the __attribute__((constructor)) in generated_ctx.c
 * 
*/
void core_set_global_ctx(Context* ctx);


/**
 * ## Build Context
 * Convenience Macro - Builds a Context on the stack from the generated registry.
 */
#define BUILD_CTX(name) \
    Context name = {_VARS, _VAR_COUNT}



/** FUTURE EXTENSION HOOKS (important for python orchestration) */

/**
 * ## Version Tag
 * Lets PyUtil and Scanner.py detect API compatibility
 */
#define ENGINE_TOOL_VERSION 1


#ifdef __cplusplus
}
#endif